### ISSUE TITLE
DyND OOC Backend

### ISSUE THREAD

**Issue by mrocklin** [blaze/blaze#284]
Currently we have backends for in memory Pandas, streaming Python, SQL, and PySpark.

Unfortunately we're missing a good C backed out of core solution.  Maybe DyND + some on disk storage could fill this void. Our working title for this is dynd.ooc, and it will operate on table data, with datashapes of the form `var * {x : T1, y : T2, ...}`.

Mark demonstrated a cool DyND OOC groupby in his work for Hugo.  (Continuum folks see [internal link](https://github.com/ContinuumIO/internal/tree/master/blazejpm)) We could extend this work to cover much of the TableExpr API. 

This would help to round out / establish  Blaze's array story. It would also be a start to "Blaze as a backend" development.
## General Plan

We'll implement a simple Table abstraction (see tasks) using in-memory DyND arrays and some simple out-of-core storage for scratch space.  OOC work will be in written in Python but may trigger the need for better in-memory `libdynd` operations.  Common use will be to open a blaze data descriptor, shove chunks into the DyND-OOC object, have it do work, and then shove chunks back into some other storage (see proposed usage).
### Tasks
- [ ] Storage - input/output from dynd.ooc a stream of chunks
- [ ] Streaming apply - apply an nd.arrfunc to every row of the table
- [ ] Filtering - filter a table based on the output of an `(...) -> bool` nd.arrfunc
- [ ] Reduction - apply reductions to the table
- [ ] Groupby - split/apply/combine
- [ ] Join - Simple inner join of two tables
### Proposed Usage

Generally DyND will 

``` Python
>>> ddesc = blaze.data.XXX(..., schema=schema)  # Blaze thing
>>> dooc = dynd.ooc.array(schema)  # DyND thing

>>> dooc.extend_chunks(ddesc.chunks())  # Shove data from data descriptor to dooc

>>> ooc_result = dooc........  # do DyND computations

>>> output = blaze.data.XXX(..., schema=schema)  # output Blaze thing
>>> output.extend_chunks(ooc_result.chunks())
```
