### ISSUE TITLE
Update Catalog Server

### ISSUE THREAD

**Issue by aterrel** [blaze/blaze#301]
The Blaze Catalog Server needs many improvements. This issue is here to track a few.
- [x] First Merge Reorg #296 
- [ ] Add yaml requirement #117 
- [ ] Fix hdf5 file names #171 
- [ ] Add hdf5 examples #172 
- [ ] Add drop #132 
- [ ] Fix dots in urls #170
